// Banco de questões V/F - Plantas Forrageiras (3ª V.A.)
// Gerado a partir de questoes_3va_plantas_forrageiras-v2.md

const QUIZ_DATA = [
  {
    modulo: "Módulo 1: Conceitos Fundamentais em Forragicultura e Alimentação Animal",
    icone: "📝",
    questoes: [
      { n: 1, texto: "Forragem compreende todas as partes comestíveis das plantas (como folhas, caules e frutos), exceto os grãos fornecidos de forma separada, que podem servir de alimento para os animais.", resposta: true, justificativa: "Por definição técnica, a forragem abrange as partes vegetativas e comestíveis colhidas ou pastejadas. Os grãos fornecidos separadamente constituem alimento concentrado, e não volumoso/forragem." },
      { n: 2, texto: "Pastagem e pasto são termos sinônimos; ambos referem-se estritamente ao ato de o animal consumir a vegetação no campo.", resposta: false, justificativa: "Pastejo é o ato voluntário do animal consumir a forragem. Pasto é a vegetação utilizada para alimentação via pastejo. Pastagem é a unidade de manejo delimitada por cercas destinadas à produção de forragem." },
      { n: 3, texto: "Os alimentos volumosos são caracterizados por apresentarem teor de fibra bruta inferior a 18% na matéria seca e elevada densidade energética.", resposta: false, justificativa: "Alimentos volumosos possuem alto teor de fibra (>18% de Fibra Bruta ou >50% de FDN) e menor teor energético. Alimentos com menos de 18% de FB são classificados como concentrados." },
      { n: 4, texto: "Uma capineira é uma cultura de gramínea forrageira, geralmente de porte alto e elevada produtividade, destinada principalmente ao corte diário para fornecimento fresco no cocho aos animais.", resposta: true, justificativa: "Esta é a definição exata de capineira (ex: cultivo de capim-elefante ou cana-de-açúcar para corte verde diário)." },
      { n: 5, texto: "Os alimentos concentrados dividem-se em energéticos (menos de 20% de proteína bruta) e proteicos (20% ou mais de proteína bruta).", resposta: true, justificativa: "Concentrados energéticos possuem <20% de PB (ex: milho em grão) e os proteicos possuem ≥20% de PB (ex: farelo de soja)." },
    ]
  },
  {
    modulo: "Módulo 2: Aspectos Qualitativos, Composição Química e Valor Nutritivo",
    icone: "🧪",
    questoes: [
      { n: 6, texto: "Qualidade da forragem e Valor Nutritivo são termos equivalentes que descrevem apenas a composição química e a digestibilidade do alimento, sem considerar a ingestão pelo animal.", resposta: false, justificativa: "Valor Nutritivo engloba composição química, digestibilidade e eficiência metabólica. Qualidade da forragem é um conceito mais abrangente: Qualidade = Valor Nutritivo + Potencial de Consumo." },
      { n: 7, texto: "A resposta animal (ganho de peso ou produção de leite) é a estimativa mais precisa da qualidade de uma forragem.", resposta: true, justificativa: "A resposta animal (desempenho produtivo) reflete a integração do consumo voluntário com a digestibilidade e absorção de nutrientes, sendo a medida definitiva da qualidade." },
      { n: 8, texto: "No fracionamento de Van Soest, a Fibra em Detergente Neutro (FDN) representa apenas a fração solúvel do conteúdo celular, possuindo digestibilidade potencial de 100%.", resposta: false, justificativa: "A FDN isola os constituintes da parede celular (hemicelulose, celulose e lignina), que possuem digestibilidade lenta e parcial. O conteúdo celular é que forma a fração solúvel." },
      { n: 9, texto: "A lignina, a cutina e a sílica são componentes da parede celular considerados completamente indigestíveis no trato gastrointestinal dos ruminantes.", resposta: true, justificativa: "Lignina, cutina e sílica constituem a fração indigestível da parede celular e ainda criam uma barreira que dificulta a degradação microbiana da celulose e hemicelulose." },
      { n: 10, texto: "À medida que uma planta forrageira atinge estádios mais avançados de maturidade, sua digestibilidade e teor de proteína bruta aumentam devido ao acúmulo de fibra na parede celular.", resposta: false, justificativa: "Com o avanço da maturidade, a qualidade da forragem declina: os teores de proteína bruta e a digestibilidade diminuem, enquanto aumentam a fração de fibra e o grau de lignificação." },
      { n: 11, texto: "Milho, sorgo, cana-de-açúcar, palma forrageira e mandioca são exceções à regra geral de queda acentuada na qualidade com a maturidade, pois acumulam carboidratos de reserva nos grãos, caules ou raízes.", resposta: true, justificativa: "Nessas plantas, o acúmulo de carboidratos de reserva nos grãos (milho/sorgo), caules (cana/palma) ou raízes (mandioca) compensa a perda de qualidade no restante dos tecidos vegetais." },
      { n: 12, texto: "As lâminas foliares de plantas forrageiras apresentam maior teor de proteína e maior digestibilidade quando comparadas aos seus respectivos caules.", resposta: true, justificativa: "As folhas contêm teores significativamente superiores de proteína bruta e maior digestibilidade da matéria seca em relação aos caules/colmos." },
      { n: 13, texto: "Gramíneas tropicais (C4) apresentam, em geral, maior teor de proteína bruta e maior digestibilidade do que gramíneas de clima temperado (C3).", resposta: false, justificativa: "Gramíneas de clima temperado (C3) são mais digestíveis (>65%) e ricas em proteína do que as gramíneas tropicais C4 (digestibilidade média entre 55% e 65%)." },
      { n: 14, texto: "As leguminosas forrageiras possuem a capacidade de fixar nitrogênio atmosférico (N₂) por meio de simbiose com bactérias dos gêneros Rhizobium e Bradyrhizobium em nódulos radiculares.", resposta: true, justificativa: "A simbiose radicular com rizóbios permite a fixação biológica de N₂, garantindo elevados teores de proteína e dispensando adubação nitrogenada mineral." },
    ]
  },
  {
    modulo: "Módulo 3: Conservação de Forragens – Fenação",
    icone: "🌾",
    questoes: [
      { n: 15, texto: "A fenação fundamenta-se na rápida desidratação da forragem fresca, reduzindo a umidade de 70–80% para 13–15% (ou 15–20%), o que paralisa a atividade respiratória celular e microbiológica.", resposta: true, justificativa: "A redução do teor de umidade para a faixa de 13–15% (ou limite de 15–20%) inibe a respiração vegetal e o crescimento de fungos e bactérias deterioradoras." },
      { n: 16, texto: "Plantas de colmos grossos e eretos, como o milheto e o milho, são as mais recomendadas para a confecção de feno devido à facilidade de secagem uniforme do material.", resposta: false, justificativa: "Colmos grossos perdem água muito lentamente, gerando secagem desuniforme. As plantas ideais para feno possuem colmos finos e elevada proporção de folhas (ex: gênero Cynodon, como Tifton e Coastcross)." },
      { n: 17, texto: "O corte da forragem para fenação no período da tarde é preferível, pois corresponde ao momento do dia com maior concentração de carboidratos solúveis nos tecidos vegetais.", resposta: true, justificativa: "À tarde, as plantas atingem o acúmulo máximo de açúcares solúveis sintetizados por fotossíntese ao longo do dia." },
      { n: 18, texto: "As reações de Maillard ocorrem quando a forragem é enfardada muito seca (<10% de umidade), resultando no aumento da digestibilidade da proteína.", resposta: false, justificativa: "As reações de Maillard ocorrem quando o feno é enfardado com excesso de umidade (>20–25%), gerando aquecimento e inutilizando a proteína (aumentando o teor de NIDA)." },
      { n: 19, texto: "O teor de matéria seca de um feno de boa qualidade não deve exceder a 20%.", resposta: false, justificativa: "O teor de matéria seca (MS) deve ser de 80% a 85%. A umidade é que deve permanecer abaixo de 15% a 20%." },
      { n: 20, texto: "Sistemas de moagem ou picagem do feno reduzem as perdas no cocho e podem aumentar o consumo voluntário pelos animais em 10% a 30% quando comparados ao feno em fibra longa.", resposta: true, justificativa: "O processamento mecânico facilita a apreensão, reduz a seleção/desperdício no cocho e incrementa a taxa de passagem e a ingestão de matéria seca." },
    ]
  },
  {
    modulo: "Módulo 4: Conservação de Forragens – Ensilagem",
    icone: "🚜",
    questoes: [
      { n: 21, texto: "A ensilagem consiste na conservação de forragens úmidas por fermentação anaeróbica, onde a produção de ácido lático rebaixa o pH e inibe microrganismos deterioradores.", resposta: true, justificativa: "A ausência de oxigênio estimula as bactérias láticas a converterem carboidratos solúveis em ácido lático, promovendo a queda do pH e preservando o alimento." },
      { n: 22, texto: "Forrageiras com alto poder tampão são ideais para a ensilagem porque facilitam o rápido rebaixamento do pH pela ação das bactérias láticas.", resposta: false, justificativa: "Alto poder tampão resiste à queda de pH, prolongando a fase de fermentação e favorecendo bactérias indesejáveis (como clostrídeos, produtores de ácido butírico)." },
      { n: 23, texto: "O milho e o sorgo são considerados as culturas padrão para ensilagem por reunirem 30–35% de matéria seca no ponto de colheita, mais de 15% de carboidratos fermentescíveis e baixo poder tampão.", resposta: true, justificativa: "Milho e sorgo combinam perfeitamente o teor ideal de MS, abundância de açúcares fermentescíveis e baixo poder tampão." },
      { n: 24, texto: "O capim-elefante colhido em estádio vegetativo jovem é excelente para ensilagem direta sem aditivos ou pré-secagem, pois apresenta elevado teor de matéria seca e de açúcares.", resposta: false, justificativa: "O capim-elefante jovem possui elevada umidade (MS <20%), baixos açúcares e alto poder tampão, levando a perdas por efluentes e fermentações secundárias se não for pré-murchado ou aditivado." },
      { n: 25, texto: "A picagem da forragem em partículas de 1 a 2 cm facilita a compactação no silo, expulsando o oxigênio e acelerando o início da fase anaeróbica.", resposta: true, justificativa: "O tamanho de partícula reduzido (1 a 2 cm) permite alta densidade de compactação e rápida eliminação do ar aprisionado." },
      { n: 26, texto: "O silo do tipo superfície apresenta menores perdas de matéria seca do que o silo do tipo trincheira.", resposta: false, justificativa: "O silo de superfície apresenta maiores perdas de MS devido à maior área exposta ao ambiente e menor eficiência de compactação nas extremidades." },
      { n: 27, texto: "Uma silagem de má qualidade (pobremente fermentada) pode apresentar altos teores de ácido butírico, ácido acético, álcool e amônia (N-amoniacal), prejudicando a palatabilidade e o consumo animal.", resposta: true, justificativa: "Fermentações secundárias (clostrídicas e por leveduras) degradam proteínas em amônia e geram odores desagradáveis que reduzem drasticamente a ingestão pelos animais." },
      { n: 28, texto: "O ponto ideal de colheita do milho para ensilagem é caracterizado pelo estádio de grão metade farináceo (linha de leite entre 1/3 e 2/3 da espiga), correspondendo a 30–35% de MS na planta inteira.", resposta: true, justificativa: "Esse estádio fenólogico garante o equilíbrio perfeito entre produtividade de MS por hectare e digestibilidade do amido e fibras." },
    ]
  },
  {
    modulo: "Módulo 5: Espécies Forrageiras Importantes (Palma, Mandioca, Milho, Sorgo, Leguminosas)",
    icone: "🌵",
    questoes: [
      { n: 29, texto: "As palmas forrageiras (Opuntia e Nopalea) possuem metabolismo fotossintético do tipo C4, o que explica sua alta eficiência no uso da água.", resposta: false, justificativa: "A palma forrageira possui metabolismo CAM (Mecanismo Ácido das Crassuláceas), captando CO₂ à noite para economizar água." },
      { n: 30, texto: "A palma forrageira é rica em carboidratos não-fibrosos (CNF) e água, possuindo alta digestibilidade, porém é deficiente em proteína bruta e fibra.", resposta: true, justificativa: "A palma supre energia rápida e água, mas necessita de complementação com fibra efetiva (para evitar diarreia/distúrbios no rúmen) e proteína bruta." },
      { n: 31, texto: "A espécie Opuntia ficus-indica é conhecida vulgarmente como palma miúda ou doce e caracteriza-se por ser totalmente resistente à praga da cochonilha-do-carmim.", resposta: false, justificativa: "Opuntia ficus-indica é a palma gigante ou graúda (suscetível). A palma miúda ou doce é a Nopalea cochenillifera (resistente à cochonilha-do-carmim)." },
      { n: 32, texto: "Os caules da palma forrageira são modificados em estruturas achatadas, carnosas e clorofiladas denominadas cladódios.", resposta: true, justificativa: "Os cladódios (ou raquetes) são caules modificados carnosos que assumiram a função fotossintética da planta." },
      { n: 33, texto: "A palma forrageira pode ser colhida e mantida armazenada à sombra por até duas semanas sem perdas aparentes na sua qualidade.", resposta: true, justificativa: "Pesquisas indicam que os cladódios da palma suportam armazenamento à sombra por até 16 dias sem alteração significativa no consumo ou valor nutricional." },
      { n: 34, texto: "Na planta de mandioca (Manihot esculenta), a concentração de glicosídeos cianogênicos (tóxicos) é maior nas folhas do que nas raízes.", resposta: true, justificativa: "A fração foliar da mandioca possui teores de glicosídeos cianogênicos (linamarina/lotaustralina) superiores aos encontrados nas raízes tuberosas." },
      { n: 35, texto: "A propagação da mandioca é feita comercialmente via sementes botânicas, e suas folhas contêm o aminoácido mimosina em altas concentrações.", resposta: false, justificativa: "A mandioca é multiplicada vegetativamente por estacas/manivas. A mimosina é o composto antinutricional/tóxico presente na leguminosa leucena." },
      { n: 36, texto: "A utilização conjunta da parte aérea (rica em proteína) e das raízes (ricas em energia/amido) da mandioca constitui uma combinação nutricional complementar para ruminantes.", resposta: true, justificativa: "A parte aérea supre proteína bruta e minerais, enquanto a raiz fornece amido altamente digestível (energia), formando uma dieta equilibrada." },
      { n: 37, texto: "A leucena (Leucaena leucocephala) é uma leguminosa arbórea de alto valor nutritivo (18 a 28% de PB), mas requer atenção quanto à presença do aminoácido mimosina.", resposta: true, justificativa: "A leucena é altamente proteica e palatável, mas a mimosina pode causar toxicidade se não houver adaptação prévia dos microrganismos do rúmen." },
      { n: 38, texto: "A cunhã (Clitoria ternatea) é uma leguminosa perene de hábito de crescimento volúvel (trepadeira), caracterizada por flores lilases/azuis e excelente valor nutritivo (12–22% PB).", resposta: true, justificativa: "A cunhã é uma leguminosa trepadeira muito adaptada, com teor proteico elevado (12–22% PB) e alta aceitabilidade pelos animais." },
      { n: 39, texto: "O milho (Zea mays) é uma gramínea cespitosa que se multiplica ativamente por rizomas e estolões, formando touceiras densas que cobrem todo o solo.", resposta: false, justificativa: "O milho é uma planta ereta, não cespitosa (geralmente desenvolve um único perfilho) e sem estruturas de propagação vegetativa como estolões ou rizomas." },
      { n: 40, texto: "O sorgo forrageiro ou de dupla aptidão apresenta maior tolerância ao estresse hídrico (seca) do que o milho, produzindo silagem de qualidade comparável.", resposta: true, justificativa: "O sorgo possui sistema radicular mais profundo e mecanismos de paralisia do crescimento durante estiagens, gerando silagens com 85% a 90% do valor nutritivo da silagem de milho." },
    ]
  },
];
